What is data manupulation ?

Data manipulation is the process converting data into a format that easy to process and is more organized

In [1]:
# Data Extraction from multiple surcess

# manupulation data using python

# organized and readable information



In [2]:
# libraries for data manipulation
# numpy pandas and scipy  matplotlib

In [3]:
# How will Numpy help in Data Science ?
# 1> first of all,it is a open source python library
# 2> It is fast because it is written in c and python
# 3> you can use in an alternative  for arrays but numpy is better ,But how is better



In [4]:
#4 what is features does Numpy provoides?

# A durable N-Dimensional array
# Tools to manipulate and work with the array
# perform mathemetical and logical operations on the array
# powerfull  pre-defined function
import numpy as np
# create  a numpy Array





In [5]:
array_1d=np.array([1,2,3,4,5,5])

In [6]:
array_1d

array([1, 2, 3, 4, 5, 5])

In [7]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [8]:
# creating the 2D array using two lists
array_2d =np.array([[2,3,4],[5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


In [9]:
print(type(array_2d))

<class 'numpy.ndarray'>


In [11]:
#creating array from list and tuple ?
array_from_list=np.array([2,5,6,7])
array_from_tuple=np.array((1,2,3,4))
print("array form list")
print(array_from_list)
print("array from tuple")
print(array_from_tuple)

array form list
[2 5 6 7]
array from tuple
[1 2 3 4]


In [12]:
#why numpy over list
# Fourier of the Numpy Library
# Linera algibra and random numbers generation
# Tools for interating c/c++
# Eassy integrating with database


In [13]:
#why numpy over Lists?

list_1 =[3,6,7,5]
list_2=[4,5,1,7]
print(len(list_1)),print(len(list_2))

4
4


(None, None)